name: Abismal Release (macOS)

on:
  workflow_dispatch:

env:
  CONTAINER: andrewdavidsmith/transferase-build

jobs:
  linux-releases:
    runs-on: macos-15
    steps:
      - name: Install dependencies
        run: |
          brew install zlib gsl automake
          brew --prefix zlib
          brew --prefix gsl
          ls -lR $(brew --prefix zlib)
          ls -lR $(brew --prefix gsl)
          git clone --recursive https://github.com/samtools/htslib.git
          cd htslib
          autoreconf -i
          mkdir build && cd build
          ../configure \
            --disable-bz2 \
            --disable-libcurl \
            --disable-lzma \
            --disable-ref-cache \
            LDADD="-L/usr/local/lib"
          make CFLAGS="-Wall -O2 -fvisibility=hidden" libhts.a
          sudo mkdir -p /opt/abismal/lib
          sudo mkdir -p /opt/abismal/include
          sudo cp libhts.a /opt/abismal/lib/
          sudo cp -r ../htslib /opt/abismal/include/
          sudo cp $(brew --prefix zlib)/lib/libz.a /opt/abismal/lib
          sudo cp -r $(brew --prefix zlib)/include/* /opt/abismal/include
          sudo cp $(brew --prefix gsl)/lib/*.a /opt/abismal/lib
          sudo cp -r $(brew --prefix gsl)/include/* /opt/abismal/include
          git clone --recursive https://github.com/smithlabcode/abismal.git
          cd abismal
          ./autogen.sh
          mkdir build && cd build
          ../configure LDFLAGS="-L/opt/abismal/lib" CPPFLAGS="-I/opt/abismal/include"
          make -j4
          ls -lh
          otool -L abismal
