name: Abismal on macOS

on:
  workflow_dispatch:

jobs:
  macos-build:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    # - uses: actions/checkout@v4
    #   with:
    #     submodules: recursive
    # - name: Update Homebrew
    #   run: brew update
    # - name: Install automake
    #   run: brew install automake
    # - name: Install dependencies
    #   run: brew install htslib
    - name: Download abismal
      # Clone and build on macOS
      run: |
        wget smithlabresearch.org/data/abismal
        chmod +x abismal
        ./abismal
        # git clone --recursive https://github.com/smithlabcode/abismal.git
        # cd abismal
        # ./autogen.sh
        # ./configure CPPFLAGS="-I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib"
        # make -j4
        # ls -ltrh
        wget smithlabresearch.org/data/xfr
        chmod +x xfr
        ./xfr
        otool -L xfr
        file xfr
        wget http://smithlab.usc.edu:80/lab/public/transferase/indexes/hg38.cpg_idx
        wget https://smithlabresearch.org:443/transferase/indexes/mm39.cpg_idx
