name: Abismal Release (macOS)

on:
  workflow_dispatch:

env:
  CONTAINER: andrewdavidsmith/transferase-build

jobs:
  linux-releases:
    runs-on: macos-15
    steps:
      - name: Install dependencies
        run: |
          brew install zlib gsl automake
          brew --prefix zlib
          brew --prefix gsl
          ls -lR $(brew --prefix zlib)
          ls -lR $(brew --prefix gsl)
          git clone --recursive https://github.com/samtools/htslib.git
          cd htslib
          autoreconf -i
          ../configure \
            --disable-bz2 \
            --disable-libcurl \
            --disable-lzma \
            --disable-ref-cache \
            LDADD="-L/usr/local/lib"
          make CFLAGS="-Wall -O2 -fvisibility=hidden" libhts.a
          sudo mkdir -p /opt/test/lib
          sudo mkdir -p /opt/test/include
          cp libhts.a /opt/test/lib/
          cp -r ../htslib /opt/test/include/
          ls -lR /opt/
          # git clone --recursive https://github.com/smithlabcode/abismal.git
          # cd abismal
          # ./autogen.sh
          # mkdir build && cd build        
