name: Brew tests

on:
  workflow_dispatch:

env:
  NCURSES_VER: 6.5
  NCURSES_FLAGS: --with-fallbacks=xterm
          --disable-database
          --enable-overwrite
          --with-normal
          --without-gpm
          --without-cxx-binding
          --disable-widec
  NCURSES_BUILD_FLAGS: -Wall
          -O2
          -DNDEBUG
          -ffunction-sections
          -fdata-sections
          -mmacosx-version-min=13

jobs:
  macos-build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: ECHO
      run: |
        echo "${NCURSES_FLAGS}"
        echo "${NCURSES_BUILD_FLAGS}"
