name: Brew tests

on:
  workflow_dispatch:

env:
  NCURSES_VER: 6.5
  NCURSES_FLAGS: --with-fallbacks=xterm \
          --disable-database \
          --enable-overwrite \
          --with-normal \
          --without-gpm \
          --without-cxx-binding \
          --disable-widec

jobs:
  macos-build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: |
        brew install googletest@1.16.0
    - name: Check
      run: |
        brew info googletest
    - name: ECHO
      run: |
        echo "${NCURSES_FLAGS}"
