name: Build things with R on macos

on:
  workflow_dispatch:

env:
  MAKEFLAGS: -j4

jobs:
  macos-build:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build with R
      run: |
        brew update
        brew install r
    - name: Install packages
      run: |
        Rscript -e "options(repos = c(CRAN = 'https://cloud.r-project.org')); install.packages(c('Rcpp', 'R6', 'roxygen2'))"
    - name: Clone transferase
      run: |
        mkdir ${HOME}/.R && \
        echo "CC=gcc-14" >> ${HOME}/.R/Makevars && \
        echo "CXX=g++-14" >> ${HOME}/.R/Makevars && \
        echo "CC23=gcc-14" >> ${HOME}/.R/Makevars && \
        echo "CXX23=g++-14" >> ${HOME}/.R/Makevars && \
        git clone https://github.com/andrewdavidsmith/transferase && \
        cd transferase && \
        cmake -B build -DBUILD_R=on -DCMAKE_INSTALL_PREFIX=rsrc -Wno-dev && \
        cmake --install build && \
        R CMD INSTALL --no-inst rsrc && \
        Rscript -e "library(roxygen2, R6); roxygen2::roxygenize('rsrc')" && \
        R CMD build rsrc && \
        R CMD check --no-manual transferase_0.5.0.tar.gz
    - name: Upload the prepared sources
      uses: actions/upload-artifact@v4
      with:
        name: rsrc-${{ matrix.os }}-${{ runner.arch }}
        path: transferase/rsrc
