name: Custom ncurses build on macos

on:
  workflow_dispatch:

env:
  NCURSES_VERSION: 6.5

jobs:
  macos-build:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build ncurses
      run: |
        # Get the source and make a build dir
        wget -nv https://ftp.gnu.org/gnu/ncurses/ncurses-${NCURSES_VERSION}.tar.gz && \
        tar -xf ncurses-${NCURSES_VERSION}.tar.gz && \
        cd ncurses-${NCURSES_VERSION} && \
        mkdir build && cd build
        # Configure the build
        ../configure --with-fallbacks=xterm \
        --disable-database \
        --enable-overwrite \
        --with-normal \
        --without-gpm \
        --disable-widec \
        --prefix=/tmp/ncurses_custom
        # Copy the fallback defs into place
        cp ${GITHUB_WORKSPACE}/fallback.c ncurses
        # Build and install
        make -j4 \
        CC=gcc-14 \
        CXX=c++-14
        make install
    - name: Upload the install directory
      uses: actions/upload-artifact@v4
      with:
        name: ncurses-custom-${{ matrix.os }}-${{ runner.arch }}
        path: /tmp/ncurses_custom
