name: Custom openssl build on macos

on:
  workflow_dispatch:

env:
  OPENSSL_VERSION: 3.4.0

jobs:
  macos-build:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Get openssl sources
    - run: |
        # Get the source and make a build dir
        wget -nv https://github.com/openssl/openssl/releases/download/openssl-${OPENSSL_VERSION}/openssl-${OPENSSL_VERSION}.tar.gz
        tar -xf openssl-${OPENSSL_VERSION}.tar.gz && \
        cd openssl-${OPENSSL_VERSION} && \
        mkdir build && cd build
        # Configure with all those options...
        cat ${GITHUB_WORKSPACE}/openssl_options.txt | \
        xargs ../Configure --prefix=/tmp/openssl_custom CC=gcc-14 CXX=g++-14
        # Build the library
        make -j4 \
        CFLAGS="-Wall -Os -fomit-frame-pointer -ffunction-sections -fdata-sections" \
        CXXFLAGS="-Wall -Os -fomit-frame-pointer -ffunction-sections -fdata-sections"
        make install
    - name: Upload the install directory
      uses: actions/upload-artifact@v4
      with:
        name: openssl-custom-${{ matrix.os }}-${{ runner.arch }}
        path: /opt/openssl_custom
