name: Conda build on macos

on:
  workflow_dispatch:

env:
  MAKEFLAGS: -j4

jobs:
  example-2-linux:
    name: Ex2 macos-15
    runs-on: macos-15
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: foo
      - name: Bash
        shell: bash -el {0}
        run: |
          conda info
          conda list
      - name: install R
        shell: bash -el {0}
        run: |
          conda install conda-forge::r-base
          find $HOME/miniconda3 -name R
      - name: Run R
        shell: bash -el {0}
        run: |
          R CMD config --all | grep CXX17
