name: Lipo universal binary on macOS

on:
  workflow_dispatch:

jobs:
  macos-build:
    runs-on: macos-15
    steps:
    - name: Configure
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Build
    - name: look
      run: |
        cmake --build build
