name: Just build main.cpp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7
      - name: Whatever
        run:
          clang++ --version
          whereis clang++
          whereis clang
          find /opt -name \*clang\* -type f
          clang++ -std=c++23 -o main main.cpp
