name: Falco Release (macOS)

on:
  workflow_dispatch:

jobs:
  build-macos:
    strategy:
      matrix:
        os: [macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone and build
        run: |
          brew install libdeflate isa-l htslib samtools &&  # samtools for testing
          git clone https://github.com/smithlabcode/falco.git &&
          cd falco &&
          git checkout falco2 &&
          cmake -B build -DUSE_ISAL=on -DCMAKE_CXX_COMPILER=g++-15 -DCMAKE_BUILD_TYPE=Release &&
          cmake --build build -j3 &&
          ctest --test-dir build
