name: Install pyxfr

on:
  workflow_dispatch:

jobs:
  install-pyxfr:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    name: Install pyxfr on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
    - name: Install pyxfr
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        pip install numpy
        pip install -i https://test.pypi.org/simple/ pyxfr
        python3 -c "import pyxfr; help(pyxfr)"
