name: Install pyxfr

on:
  workflow_dispatch:

jobs:
  install-pyxfr:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
        py: ['3.12', '3.13']
    name: Install pyxfr on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.py}}
      - name: Install pyxfr
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install numpy
          pip install -i https://test.pypi.org/simple/ pyxfr
          python -c "import pyxfr; help(pyxfr)"
