name: None

on:
  workflow_dispatch:

env:
  MAKEFLAGS: -j4

jobs:
  build-r:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Look first
        run: |
          whereis pdflatex
      - name: Update Homebrew
        run: |
          brew update
      - name: Install LaTeX
        run: |
          brew install basictex
      - name: Look second
        run: |
          eval "$(/usr/libexec/path_helper)"
          whereis pdflatex
      - name: get the font
        run: |
          brew install --cask font-inconsolata
          sudo find /usr -name \*inconsola\*
      - name: find the font bb
        run: |
          sudo tlmgr update --self
          sudo tlmgr update --all
          sudo tlmgr install titling framed inconsolata
          sudo tlmgr install collection-fontsrecommended
      - name: find the font 2
        run: |
          sudo find /usr -name \*.sty
