name: None

on:
  workflow_dispatch:

env:
  MAKEFLAGS: -j4

jobs:
  build-r:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Look first
        run: |
          whereis pdflatex
      - name: Update Homebrew
        run: |
          brew update
      - name: Install LaTeX
        run: |
          sudo ls -l /usr/local
          brew install basictex
      - name: Look second
        run: |
          sudo ls -l /usr/local
          sudo ls -l $(brew --prefix)
          eval "$(/usr/libexec/path_helper)"
          whereis pdflatex
      - name: find the font bb
        run: |
          eval "$(/usr/libexec/path_helper)"
          sudo tlmgr update --self
          sudo tlmgr install inconsolata
      - name: find the font 2
        run: |
          sudo find /usr -name \*.sty
      - name: Find OpenSSL
        run: |
          brew --prefix openssl
      - name: Link /usr/local to Homebrew
        run: |
          echo Brew prefix
          brew --prefix
          echo Listing Brew prefix
          ls -l $(brew --prefix)
          sudo ln -s $(brew --prefix)/include /usr/local/include
          sudo ln -s $(brew --prefix)/lib /usr/local/lib
          echo Now usr local
          ls -l /usr/local
      - name: see clang search path
        run: |
          echo | clang -E -Wp,-v -
      - name: brew prefix
        run: |
          brew --prefix
          ls $(brew --prefix)
