name: None2

on:
  workflow_dispatch:

env:
  MAKEFLAGS: -j4

jobs:
  build-r:
    strategy:
      matrix:
        os: [macos-15]
        python: [3.12, 3.13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Look at Python ${{ matrix.python }}
        run: |
          python${{ matrix.python }} --version
