name: Build on macOS

on:
  workflow_dispatch:

jobs:
  macos-build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: See Effective Triple
      run: clang -print-effective-triple
    - name: See Supported CPUs
      run: clang -print-supported-cpus
    - name: See Target Triple
      run: clang -print-target-triple
    - name: See Targets
      run: clang -print-targets
    - name: See Targets
      run: clang -mcpu=help
    - name: make
      run: |
        export CC=clang
        make universal_app
    - name: look
      run: ls -ltrh .
    - name: check out the GCC arch options
      run: |
        gcc-14 --target-help 2>&1
