name: Build on macOS

on:
  workflow_dispatch:

jobs:
  macos-build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: See Effective Triple
      run: clang -print-effective-triple
    - name: See Supported CPUs
      run: clang -print-supported-cpus
    - name: See Target Triple
      run: clang -print-target-triple
    - name: See Targets
      run: clang -print-targets
    - name: Build
      run: |
        cmake -B build -DCMAKE_VERBOSE_MAKEFILE=on -DCMAKE_BUILD_TYPE=Build
    - name: Build
      run: |
        cmake --build build
        ls
    - name: Check that it runs
      run: |
        ./build/main
