name: Reuse artifacts

on:
  workflow_dispatch:

jobs:
  macos-build:
    strategy:
      matrix:
        os: [macos-13, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure ${{ matrix.os }}
        run: |
          cmake -B build_${{matrix.os}} -DCMAKE_VERBOSE_MAKEFILE=on -DCMAKE_CXX_COMPILER=g++-14 -DCMAKE_OSX_DEPLOYMENT_TARGET=14 -DCMAKE_BUILD_TYPE=Build
      - name: Build
        run: |
          cmake --build build_${{matrix.os}}
      - name: Look
        run: |
          ls -lR
      - name: Check the file
        run: |
          file build_${{matrix.os}}/main
          file build_${{matrix.os}}/libmylib.a
          otool -L build_${{matrix.os}}/main
      - name: Upload the binary
        uses: actions/upload-artifact@v4
        with:
          name: main_${{matrix.os}}
          path: build_${{matrix.os}}/main
  download:
    needs: macos-build
    runs-on: macos-15
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: mains
          pattern: main_*
          merge-multiple: false
      - run: |
          ls -R my-artifact
    
