name: Rxfr

on:
  workflow_dispatch:

env:
  MAKEFLAGS: -j4

jobs:
  build-r:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Update Homebrew
        run: |
          brew update
      - name: Install OpenSSL
        run: |
          brew install openssl
      - name: Get Rxfr
        run: |
          wget https://github.com/andrewdavidsmith/transferase/releases/download/v0.6.2/Rxfr_0.6.2.tar.gz
      - name: Install R
        run: |
          brew install --cask r
      - name: Link the Brew prefix paths
        run: |
          echo $(brew --prefix)
          sudo ln -s $(brew --prefix)/include /usr/local/include
          sudo ln -s $(brew --prefix)/lib /usr/local/lib
      - name: Install R dependencies
        run: |
          R -e 'install.packages(c("R6", "Rcpp", "roxygen2"), repos = "https://cloud.r-project.org")'
      - name: Install the package
        run: |
          R -e 'install.packages(c("Rxfr_0.6.2.tar.gz"))'
          R -e 'library(Rxfr)'
