name: Test lipo file

on:
  workflow_dispatch:

jobs:
  build-wheel:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    name: "Lipo ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the lipo
        run: |
          wget https://smithlabresearch.org/transferase/transferase
      - name: Run the lipo
        run: |
          ./transferase
          ./transferase query --help
